//import modules
const fs = require("fs");

const express = require("express");
const mongoose = require("mongoose");
const userRoutes = require("./routes/user");
const OpenAI = require("openai");
const cors = require("cors");

require("dotenv").config();

const PORT = process.env.PORT;
const CHAT_PORT = process.env.CHAT_PORT;

console.log(PORT);

//OpenAI's API
const openai = new OpenAI({
  apiKey: "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",
});

// express app
const app = express();

// Enable CORS for all routes
app.use(cors());

// middleware
app.use(express.json());

app.use((req, res, next) => {
  console.log(req.path, req.method);
  next();
});

app.get("/", (req, res) => res.send("Express on Vercel"));

app.listen(CHAT_PORT, () => console.log(`Server ready on port ${CHAT_PORT}.`));

// routes
app.use("/api/user", userRoutes);

// connect to db
mongoose
  .connect(process.env.MONG_URI)
  .then(() => {
    // listen for requests
    app.listen(process.env.PORT, () => {
      console.log("connected to db & listening on port", process.env.PORT);
    });
  })
  .catch((error) => {
    console.log(error);
  });

app.post("/chat", async (req, res) => {
  try {
    const response = await openai.chat.completions.create({
      model: "gpt-3.5-turbo",
      messages: [
        {
          role: "system",
          content:
            "pretend to be GabAi\n\nGabAi is an AI dedicated to assisting victims of workplace discrimination in the Philippines, providing legal guidance and support. GabAi adopts an empathetic, supportive, and respectful tone and mood, while maintaining professionalism, honesty, and assertiveness, coupled with encouragement and confidentiality. \n\nhere's context law sample:\n\nREPUBLIC ACT NO. 9710\nAN ACT PROVIDING FOR THE MAGNA CARTA OF WOMEN'S CHAPTER 1\n\nCHAPTER I GENERAL PROVISIONS\nSECTION 1. SHORT TITLE. — THIS ACT SHALL BE KNOWN AS “THE MAGNA CARTA OF WOMEN”.\nSECTION 2. DECLARATION OF POLICY. — RECOGNIZING THAT THE ECONOMIC, POLITICAL, AND SOCIOCULTURAL REALITIES AFFECT WOMEN’S CURRENT CONDITION, THE STATE AFFIRMS THE ROLE OF WOMEN IN NATION BUILDING AND ENSURES THE SUBSTANTIVE EQUALITY OF WOMEN AND MEN. IT SHALL PROMOTE EMPOWERMENT OF WOMEN AND PURSUE EQUAL OPPORTUNITIES FOR WOMEN AND MEN AND ENSURE EQUAL ACCESS TO RESOURCES AND TO DEVELOPMENT RESULTS AND OUTCOME. FURTHER, THE STATE REALIZES THAT EQUALITY OF MEN AND WOMEN ENTAILS THE ABOLITION OF THE UNEQUAL STRUCTURES AND PRACTICES THAT PERPETUATE DISCRIMINATION AND INEQUALITY. TO REALIZE THIS, THE STATE SHALL ENDEAVOR TO DEVELOP PLANS, POLICIES, PROGRAMS, MEASURES, AND MECHANISMS TO ADDRESS DISCRIMINATION AND INEQUALITY IN THE ECONOMIC, POLITICAL, SOCIAL, AND CULTURAL LIFE OF WOMEN AND MEN.\nTHE STATE CONDEMNS DISCRIMINATION AGAINST WOMEN IN ALL ITS FORMS AND PURSUES BY ALL APPROPRIATE MEANS AND WITHOUT DELAY THE POLICY OF ELIMINATING DISCRIMINATION AGAINST WOMEN IN KEEPING WITH THE CONVENTION ON THE ELIMINATION OF ALL FORMS OF DISCRIMINATION AGAINST WOMEN (CEDAW) AND OTHER INTERNATIONAL INSTRUMENTS CONSISTENT WITH PHILIPPINE LAW. THE STATE SHALL ACCORD WOMEN THE RIGHTS, PROTECTION, AND OPPORTUNITIES AVAILABLE TO EVERY MEMBER OF SOCIETY.\nTHE STATE AFFIRMS WOMEN’S RIGHTS AS HUMAN RIGHTS AND SHALL INTENSIFY ITS EFFORTS TO FULFILL ITS DUTIES UNDER INTERNATIONAL AND DOMESTIC LAW TO RECOGNIZE, RESPECT, PROTECT, FULFILL, AND PROMOTE ALL HUMAN RIGHTS AND FUNDAMENTAL FREEDOMS OF WOMEN, ESPECIALLY MARGINALIZED WOMEN, IN THE ECONOMIC, SOCIAL, POLITICAL, CULTURAL, AND OTHER FIELDS WITHOUT DISTINCTION OR DISCRIMINATION ON ACCOUNT OF CLASS, AGE, SEX, GENDER, LANGUAGE, ETHNICITY, RELIGION, IDEOLOGY, DISABILITY, EDUCATION, AND STATUS.\nTHE STATE SHALL PROVIDE THE NECESSARY MECHANISMS TO ENFORCE WOMEN’S RIGHTS AND ADOPT AND UNDERTAKE ALL LEGAL MEASURES NECESSARY TO FOSTER AND PROMOTE THE EQUAL OPPORTUNITY FOR WOMEN TO PARTICIPATE IN AND CONTRIBUTE TO THE DEVELOPMENT OF THE POLITICAL, ECONOMIC, SOCIAL, AND CULTURAL REALMS.\nTHE STATE, IN ENSURING THE FULL INTEGRATION OF WOMEN’S CONCERNS IN THE MAINSTREAM OF DEVELOPMENT, SHALL PROVIDE AMPLE OPPORTUNITIES TO ENHANCE AND DEVELOP THEIR SKILLS, ACQUIRE PRODUCTIVE EMPLOYMENT AND CONTRIBUTE TO THEIR FAMILIES AND COMMUNITIES TO THE FULLEST OF THEIR CAPABILITIES.\nIN PURSUANCE OF THIS POLICY, THE STATE REAFFIRMS THE RIGHT OF WOMEN IN ALL SECTORS TO PARTICIPATE IN POLICY FORMULATION, PLANNING, ORGANIZATION, IMPLEMENTATION, MANAGEMENT, MONITORING, AND EVALUATION OF ALL PROGRAMS, PROJECTS, AND SERVICES. IT SHALL SUPPORT POLICIES, RESEARCHES, TECHNOLOGY, AND TRAINING PROGRAMS AND OTHER SUPPORT SERVICES SUCH AS FINANCING, PRODUCTION, AND MARKETING TO ENCOURAGE ACTIVE PARTICIPATION OF WOMEN IN NATIONAL DEVELOPMENT.\nSECTION 3. PRINCIPLES OF HUMAN RIGHTS OF WOMEN. — HUMAN RIGHTS ARE UNIVERSAL AND INALIENABLE. ALL PEOPLE IN THE WORLD ARE ENTITLED TO THEM. THE UNIVERSALITY OF HUMAN RIGHTS IS ENCOMPASSED IN THE WORDS OF ARTICLE 1 OF THE UNIVERSAL DECLARATION OF HUMAN RIGHTS, WHICH STATES THAT ALL HUMAN BEINGS ARE FREE AND EQUAL IN DIGNITY AND RIGHTS.\nHUMAN RIGHTS ARE INDIVISIBLE. HUMAN RIGHTS ARE INHERENT TO THE DIGNITY OF EVERY HUMAN BEING WHETHER THEY RELATE TO CIVIL, CULTURAL, ECONOMIC, POLITICAL, OR SOCIAL ISSUES.\nHUMAN RIGHTS ARE INTERDEPENDENT AND INTERRELATED. THE FULFILLMENT OF ONE RIGHT OFTEN DEPENDS, WHOLLY OR IN PART, UPON THE FULFILLMENT OF OTHERS.\nALL INDIVIDUALS ARE EQUAL AS HUMAN BEINGS BY VIRTUE OF THE INHERENT DIGNITY OF EACH HUMAN PERSON. NO ONE, THEREFORE, SHOULD SUFFER DISCRIMINATION ON THE BASIS OF ETHNICITY, GENDER, AGE, LANGUAGE, SEXUAL ORIENTATION, RACE, COLOR, RELIGION, POLITICAL, OR OTHER OPINION, NATIONAL, SOCIAL, OR GEOGRAPHICAL ORIGIN, DISABILITY, PROPERTY, BIRTH, OR OTHER STATUS AS ESTABLISHED BY HUMAN RIGHTS STANDARDS.\nALL PEOPLE HAVE THE RIGHT TO PARTICIPATE IN AND ACCESS INFORMATION RELATING TO THE DECISION-MAKING PROCESSES THAT AFFECT THEIR LIVES AND WELL-BEING. RIGHTS-BASED APPROACHES REQUIRE A HIGH DEGREE OF PARTICIPATION BY COMMUNITIES, CIVIL SOCIETY, MINORITIES, WOMEN, YOUNG PEOPLE, INDIGENOUS PEOPLES, AND OTHER IDENTIFIED GROUPS.\nSTATES AND OTHER DUTY-BEARERS ARE ANSWERABLE FOR THE OBSERVANCE OF HUMAN RIGHTS. THEY HAVE TO COMPLY WITH THE LEGAL NORMS AND STANDARDS ENSHRINED IN INTERNATIONAL HUMAN RIGHTS INSTRUMENTS IN ACCORDANCE WITH THE PHILIPPINE CONSTITUTION. WHERE THEY FAIL TO DO SO, AGGRIEVED RIGHTS-HOLDERS ARE ENTITLED TO INSTITUTE PROCEEDINGS FOR APPROPRIATE REDRESS BEFORE A COMPETENT COURT OR OTHER ADJUDICATOR IN ACCORDANCE WITH THE RULES AND PROCEDURES PROVIDED BY LAW.",
        },
      ],
      temperature: 1,
      max_tokens: 4095,
      top_p: 1,
      frequency_penalty: 0.54,
      presence_penalty: 0.49,
    });
    // Extract the chatbot's response from the API response
    const chatbotResponse = response.data.choices[0].message.content;

    // Send the chatbot's response back to the frontend
    res.json({ message: chatbotResponse });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: error.message });
  }
});

module.exports = app;
