import React, { useState } from "react";
import { Helmet } from "react-helmet";
import pdfMake from "pdfmake/build/pdfmake"; // Import pdfmake library
import pdfFonts from "pdfmake/build/vfs_fonts"; // Import fonts for pdfmake
import TotalList from "../../components/admin/TotalList";
import AllDemo from "../../components/admin/AllDemo";
// CSS
import "../../css/admin-dashboard.css";

pdfMake.vfs = pdfFonts.pdfMake.vfs; // Set the fonts for pdfmake

function AdminDashboard() {
  const name = "Admin";

  const [locationData, setLocationData] = useState({
    Region1: 0,
    Region2: 0,
    Region3: 0,
    Region4: 0,
    Region5: 0,
    Region6: 0,
    Region7: 0,
    Region8: 0,
    Region9: 0,
    Region10: 0,
    Region11: 0,
    Region12: 0,
    CAR: 0,
    CARAGA: 0,
    NCR: 0,
    ARMM: 0,
  });

  const generateReport = () => {
    const userData = {
      totalUsers: 0,
      male: 0,
      female: 0,
      preferNotToSay: 0,
      lgbtq: 0,
      age1820: 0,
      age2130: 0,
      age3140: 0,
      age4150: 0,
      age5160: 0,
      age60Above: 0,
    };
    const caseData = {
      totalCases: 0,
    };
    const currentDate = new Date().toLocaleDateString();
    const currentTime = new Date().toLocaleTimeString();

    const docDefinition = {
      content: [
        { text: "Workplace Discrimination Report", style: "title" },
        { text: `Generated by: ${name}`},
        { text: `Date: ${currentDate} Time: ${currentTime}` },
        { text: "Summary of Data", style: "subheader" },
        { text: `Total Users: ${userData.totalUsers}`, margin: [0, 10, 0, 0] },
        { text: `Gender Distribution:
          - Male: ${userData.male}
          - Female: ${userData.female}
          - Prefer Not to Say: ${userData.preferNotToSay}
          - LGBTQ+: ${userData.lgbtq}`, margin: [0, 5, 0, 0] },
        { text: `Total Cases: ${caseData.totalCases}`, margin: [0, 5, 0, 0] },
        { text: `Age Distribution:
          - 18-20: ${userData.age1820}
          - 21-30: ${userData.age2130}
          - 31-40: ${userData.age3140}
          - 41-50: ${userData.age4150}
          - 51-60: ${userData.age5160}
          - 60 and Above: ${userData.age60Above}`, margin: [0, 5, 0, 0] },
        {
          columns: [
            {
              text: "Location Distribution:",
              margin: [0, 10, 0, 0],
            },
            {
              text: "",
            },
          ],
        },
        {
          columns: [
            
            {
              text: Object.entries(locationData).map(([key, value]) => `${key}: ${value === 0 ? "0" : value}`).join("\n"),
            },
          ],
        },
        {
          text:
            "This report provides an overview of the current state of workplace demographics and discrimination-related incidents. It highlights the total number of users, gender distribution, total cases, age distribution, and location distribution. By understanding these factors, proactive measures can be taken to address discrimination and promote diversity and inclusion in the workplace.",
          margin: [0, 10, 0, 20],
        },
      ],
      styles: {
        title: {
          fontSize: 18,
          bold: true,
          alignment: "center",
          margin: [0, 0, 0, 10],
        },
        subheader: {
          fontSize: 14,
          bold: true,
          margin: [0, 10, 0, 5],
        },
      },
    };

    const pdfDoc = pdfMake.createPdf(docDefinition);
    pdfDoc.download(`workplace_discrimination_report_${currentDate}_${currentTime}.pdf`);
  };

  return (
    <>
      <Helmet>
        {/* Title of the Page */}
        <title>Admin Dashboard - GabAI</title>
      </Helmet>

      <div className="relative z-10 w-full pt-[3.875rem] flex flex-col justify-start items-center min-h-screen max-md:p-1 bg-bkg text-content">
        <div id="main-content" className="flex flex-col w-full mx-auto max-w-5xl">
          {/* Contents */}
          <div className="mt-0">
            <h1 className="text-2xl font-semibold">Welcome, {name}!</h1>
          </div>

          {/* Shows the Number of Users, Cases, etc. */}
          <TotalList />
          <div className="flex flex-col justify-stretch items-stretch mt-2">
            <AllDemo />
          </div>

         
        </div>
        <br/>
         {/* Button to generate report */}
          <button
            onClick={generateReport}
            className="rounded-xl bg-azure-500 px-4 py-1.5 text-white hover:scale-[1.1] transition-all duration-100 ease-in-out relative z-10 after:absolute after:-z-20  after:h-1 after:w-1 after:bg-azure-300 after:left-5 overflow-hidden after:bottom-0 after:translate-y-full after:rounded-md after:hover:scale-[50] after:hover:transition-all after:hover:duration-650 after:transition-all after:duration-300 hidden md:block"
          >
            Generate Report
          </button>
      </div>
    </>
  );
}

export default AdminDashboard;
